
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author knowx200
 */
public class ChurnMap extends javax.swing.JFrame {

    /**
     * Creates new form ChurnMap
     */
    public ChurnMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Upload DataSet to HDFS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 210, 274, 44);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Phone Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 330, 200, 42);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 320, 274, 48);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(409, 424, 145, 37);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(38, 108, 160, 41);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setText("CHURN DISCOVERY UPLOAD DATASET");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 0, 720, 50);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Upload Dataset");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 210, 200, 42);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mapp_1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        Menu m=new Menu();
        m.setVisible(true);
        m.setSize(1000,670 );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	try{
			File file = new File("dataset/Churn.txt");
			if(file.exists()){
				String datasetPath = file.getCanonicalPath();
				String command = "hdfs dfs -put -f "+datasetPath.trim();
				System.out.println(command);
				Process p1 = Runtime.getRuntime().exec(command);
				BufferedReader stdinput1 = new BufferedReader(new InputStreamReader(p1.getInputStream()));
				String s1 = "";
				while((s1 = stdinput1.readLine())!=null)
				{
					System.out.println(s1);
				}	
				System.out.println(new File(datasetPath).getName()+" file uploaded to HDFS");
				JOptionPane.showMessageDialog(null, "File Uploaded to HDFS");
			}
			
		}
		catch(Exception e1)
		{
			System.out.println(e1);
		}
    	//JOptionPane.showMessageDialog(null, "upload dataset to HDfs");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	String phone,check="";
		
		String res="";
		phone=jTextField1.getText();
		
		try{
			Runtime.getRuntime().exec("hdfs dfs -rmr Churnfinal");
		System.out.println("calling ./Hadoop_jars/churn.jar");
		File file = new File("./Hadoop_jars/churn.jar");
		String command = "hadoop jar Hadoop_jars/churn.jar Client1 "+phone;
		System.out.println(command);
		Process p1 = Runtime.getRuntime().exec(command);

		BufferedReader stdinput1 = new BufferedReader(new InputStreamReader(p1.getInputStream()));
		String s1 = "";
		while((s1 = stdinput1.readLine())!=null)
		{
			System.out.println(s1);
		}				
		JOptionPane.showMessageDialog(null, "Filter based on Phone Number is completed sucessfully!!!");
		
		System.out.println("completed");
		
//
		Process p = Runtime.getRuntime().exec("hdfs dfs -cat Churnfinal/part-00000");

		BufferedReader stdinput = new BufferedReader(new InputStreamReader(p.getInputStream()));
		String s = "";
		StringBuffer finalResult = new StringBuffer("");
		StringBuffer finalResultToDisplay = new StringBuffer("");
		while((s = stdinput.readLine())!=null)
		{
			finalResult.append(s);
		}
		if(finalResult.toString().trim().length() !=0)
		{
			String asd_splits[] = finalResult.toString().split(",");
			finalResultToDisplay.append("Churn Information \n");
			finalResultToDisplay.append("Account Length : "+asd_splits[0]+"\n");
			finalResultToDisplay.append("Vmail Message : "+asd_splits[1]+"\n");
			finalResultToDisplay.append("Day Min : "+asd_splits[2]+"\n");
			finalResultToDisplay.append("Eve Min : "+asd_splits[3]+"\n");
			finalResultToDisplay.append("Night Min : "+asd_splits[4]+"\n");
			finalResultToDisplay.append("Intl Min : "+asd_splits[5]+"\n");
			finalResultToDisplay.append("Customer Service Call: "+asd_splits[6]+"\n");
			finalResultToDisplay.append("Churn : "+asd_splits[7]+"\n");
			finalResultToDisplay.append("Int'l Plan : "+asd_splits[8]+"\n");
			finalResultToDisplay.append("VMain Plan : "+asd_splits[9]+"\n");
			finalResultToDisplay.append("Day Calls : "+asd_splits[10]+"\n");
			finalResultToDisplay.append("Day Charge: "+asd_splits[11]+"\n");
			finalResultToDisplay.append("Evening calls : "+asd_splits[12]+"\n");
			finalResultToDisplay.append("Evening Charge : "+asd_splits[13]+"\n");
			finalResultToDisplay.append("Nigth Call : "+asd_splits[14]+"\n");
			finalResultToDisplay.append("Night Charge : "+asd_splits[15]+"\n");
			finalResultToDisplay.append("Intl Calls : "+asd_splits[16]+"\n");
			finalResultToDisplay.append("Intl Charge : "+asd_splits[17]+"\n");
			finalResultToDisplay.append("State : "+asd_splits[18]+"\n");
			finalResultToDisplay.append("Area Code : "+asd_splits[19]+"\n");
			finalResultToDisplay.append("Phone number : "+asd_splits[20]+"\n");
			
			

		}

		
		JOptionPane.showMessageDialog(null, finalResultToDisplay);
		
	
		}
		catch(Exception e2)
		{
			System.out.println("ex"+ e2);
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChurnMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChurnMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChurnMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChurnMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChurnMap ch=new ChurnMap();
                ch.setSize(1000,670);
                ch.setVisible(true);
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
