/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author comp
 */
public class DataAnalysis extends javax.swing.JFrame {

    ArrayList<String> allAttributes=new ArrayList<String>();
    public DataAnalysis() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }
    
    public DataAnalysis(ArrayList<String> arr1) {
        
       initComponents();
       this.getContentPane().setBackground(Color.white);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attr = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prioritizing the Attributes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 30, 650, 50);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Attributes:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 180, 300, 29);

        attr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attr.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "AccountLength", "DayMins", "EveMins", "NightMins", "IntlMins", "DayCalls", "DayCharge", "EveCalls", "EveCharge", "NightCalls", "NightCharge", "IntlCalls", "State", "AreaCode", "Phone" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(attr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 210, 360, 200);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Apply Aprori Algorithm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 450, 280, 44);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("Display Phone no with Churn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 540, 280, 44);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton4.setText("Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 40, 160, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map.jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(1000, 670));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 670);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 10, 34, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        allAttributes.clear();
        allAttributes.add("AccountLength");
        allAttributes.add("DayMins");
        allAttributes.add("EveMins");
        allAttributes.add("NightMins");
        allAttributes.add("IntlMins");
        allAttributes.add("DayCalls");
        allAttributes.add("DayCharge");
        allAttributes.add("EveCalls");
        allAttributes.add("EveCharge");
        allAttributes.add("NightCalls");
        allAttributes.add("NightCharge");
        allAttributes.add("IntlCalls");
        allAttributes.add("State");
        allAttributes.add("AreaCode");
        allAttributes.add("Phone");
        Object obj[] = attr.getSelectedValues();
         ArrayList<String> allAttr = new ArrayList<>();
         allAttr.clear();
         for(int i=0;i<obj.length;i++){
             allAttr.add((String)obj[i]);
         }
         System.out.println("allAttr"+allAttr);
         System.out.println("allAttributes"+allAttributes);
         AprioriFrame ap = new AprioriFrame(allAttributes, allAttr);
         ap.setVisible(true);
         ap.setSize(600,600);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        allAttributes.clear();
        allAttributes.add("AccountLength");
        allAttributes.add("DayMins");
        allAttributes.add("EveMins");
        allAttributes.add("NightMins");
        allAttributes.add("IntlMins");
        allAttributes.add("DayCalls");
        allAttributes.add("DayCharge");
        allAttributes.add("EveCalls");
        allAttributes.add("EveCharge");
        allAttributes.add("NightCalls");
        allAttributes.add("NightCharge");
        allAttributes.add("IntlCalls");
        allAttributes.add("State");
        allAttributes.add("AreaCode");
        allAttributes.add("Phone");
        Object obj[] = attr.getSelectedValues();
         ArrayList<String> allAttr = new ArrayList<>();
         allAttr.clear();
         for(int i=0;i<obj.length;i++){
             allAttr.add((String)obj[i]);
         }
         System.out.println("allAttributes"+allAttributes);
         System.out.println("allAttr"+allAttr);
         AttrRead aa=new AttrRead(allAttributes, allAttr);
         aa.setVisible(true);
         aa.setSize(600,600);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        Menu m=new Menu();
        m.setVisible(true);
        m.setSize(1000,670 );
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataAnalysis dd=new DataAnalysis();
                dd.setVisible(true);
                dd.setSize(1000, 670);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> attr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
